/**
 * Content for the comparison pages. Prices mirror the service pages; keep them in sync.
 */
import type { ComparisonData } from "@/components/ComparisonPage";

export const PPF_VS_CERAMIC: ComparisonData = {
  path: "/ppf-vs-ceramic-coating",
  title: "Full Front PPF vs Ceramic Coating: Which Do You Need?",
  description: "PPF vs ceramic coating compared side by side: rock chips, scratches, gloss, cost, lifespan, and maintenance. Which one Chantilly, VA drivers need, and when to do both.",
  eyebrow: "PPF vs ceramic coating",
  h1: "PPF VS CERAMIC COATING: WHICH ONE DO YOU ACTUALLY NEED?",
  intro: "They get sold as if they were rivals, but paint protection film and ceramic coating solve different problems. Film is a physical barrier that stops rock chips and scratches. A coating is a chemical layer that makes paint glossier, slicker, and easier to wash. This is how we explain the difference to customers in our Chantilly bay every week, with the same numbers we quote them.",
  breadcrumb: "PPF vs Ceramic Coating",
  columns: [
    { key: "ppf", name: "Paint Protection Film", sub: "STEK DYNOshield", href: "/services/ppf", bestFor: "Stopping rock chips, gravel, and scratches on the front end. The only product that physically absorbs impacts." },
    { key: "ceramic", name: "Ceramic Coating", sub: "Gtechniq Crystal Serum", href: "/services/ceramic-coating", bestFor: "Gloss, easier washing, and protection from UV, bird droppings, and water spots across the whole car." },
    { key: "both", name: "PPF + Ceramic", sub: "Our most common combo", href: "/get-a-quote?service=ppf", bestFor: "New cars and anything you plan to keep. Film where chips happen, coating everywhere for gloss and maintenance." },
  ],
  rows: [
    { label: "Rock chips & gravel", cells: { ppf: { mark: "yes", text: "Yes. 8-mil urethane absorbs the impact." }, ceramic: { mark: "no", text: "No. A coating is microns thick and will not stop a chip." }, both: { mark: "yes", text: "Yes, on every filmed panel." } } },
    { label: "Light scratches & swirls", cells: { ppf: { mark: "yes", text: "Yes. Self-healing top coat closes light scratches with heat." }, ceramic: { mark: "partial", text: "Slightly harder surface, but still swirls from bad washing." }, both: { mark: "yes", text: "Film heals; coating resists new swirls." } } },
    { label: "Gloss & depth", cells: { ppf: { mark: "partial", text: "Clear film keeps the factory look; matte option available." }, ceramic: { mark: "yes", text: "Noticeably deeper gloss after paint correction." }, both: { mark: "yes", text: "Coating on top of film adds the gloss." } } },
    { label: "Easier washing & water beading", cells: { ppf: { mark: "partial", text: "DYNOshield is hydrophobic, but a coating beads better." }, ceramic: { mark: "yes", text: "Yes. Dirt releases with a rinse; no wax needed." }, both: { mark: "yes", text: "Best case: the whole car washes the same way." } } },
    { label: "UV, bird droppings, water spots", cells: { ppf: { mark: "yes", text: "Film takes the etching instead of the paint." }, ceramic: { mark: "yes", text: "Chemical resistance is what coatings are for." }, both: { mark: "yes", text: "Covered everywhere." } } },
    { label: "Coverage", cells: { ppf: { text: "Front end: hood, bumper, fenders, mirrors, headlights. Full front extended adds rockers and door edges." }, ceramic: { text: "Whole car including glass, trim, and wheels on the Crystal Serum Ultra package." }, both: { text: "Front end filmed, entire car coated." } } },
    { label: "Lifespan & warranty", cells: { ppf: { text: "12-year STEK manufacturer warranty." }, ceramic: { text: "5-year (Crystal Serum Light) or 7-year (Crystal Serum Ultra) warranty." }, both: { text: "Each layer carries its own warranty." } } },
    { label: "Install time", cells: { ppf: { text: "1 day for a full front; 1–2 days for full front extended." }, ceramic: { text: "1–2 days including paint correction." }, both: { text: "2–3 days, done in one visit." } } },
    { label: "Removable?", cells: { ppf: { mark: "yes", text: "Yes, cleanly, with no damage to factory paint." }, ceramic: { mark: "no", text: "It is bonded; it wears off over years or is polished off." }, both: { text: "Film removable; coating permanent until worn." } } },
  ],
  verdicts: [
    { title: "Get PPF if…", body: "You commute on I-66, Route 28, or the Dulles Toll Road, you just bought a new car, or you already have chips on the bumper and hood. Nothing else stops the next one.", href: "/services/ppf", cta: "PPF packages" },
    { title: "Get ceramic if…", body: "The paint is in good shape, you mostly drive local, and what you want is gloss and a car that stays clean with a quick rinse instead of a weekend of waxing.", href: "/services/ceramic-coating", cta: "Coating packages" },
    { title: "Get both if…", body: "You plan to keep the car three years or more. Film on the front, coating on everything. Ask about this month's special when you request a quote; we often bundle full front PPF with a ceramic coating.", href: "/promo", cta: "This month's special" },
  ],
  faqs: [
    { q: "Does ceramic coating protect against rock chips?", a: "No. A ceramic coating is a few microns thick and cannot absorb an impact. It resists chemicals, UV, and light marring. If chips are the problem, you need paint protection film." },
    { q: "Can you put ceramic coating over PPF?", a: "Yes, and we recommend it. Coating bonds well to STEK DYNOshield, adds gloss, and makes the film easier to keep clean. It does not affect the film's self-healing or its warranty." },
    { q: "Which is cheaper, PPF or ceramic coating?", a: "A ceramic coating for the whole car costs less up front than film on the front end, because film is a thick physical layer that is cut and fitted panel by panel. They protect against different things, so the right question is which damage you are trying to prevent. Request a free quote and we will price both for your car." },
    { q: "How long does each one last?", a: "STEK DYNOshield PPF carries a 12-year warranty. Gtechniq coatings are warrantied for 5 years (Crystal Serum Light) or 7 years (Crystal Serum Ultra). Both depend on washing the car properly and avoiding automatic brush washes." },
    { q: "Is PPF worth it on a leased car?", a: "Often yes. Chips on the bumper and hood are exactly what lease-return inspections charge for, and film is removable with no damage to the paint. A partial or full front usually costs less than one repaint." },
    { q: "Do I need paint correction before either one?", a: "Every ceramic coating package includes paint correction because the coating locks in whatever is under it. PPF also goes on after a decontamination wash and any needed correction so the film sits over clean, defect-free paint." },
  ],
  videoIds: ["kfzGx2IROLg", "ZvVdjXH06ug", "dI6_E2HSmmE", "euOKAH_QStE"],
  related: [
    { label: "PPF packages & pricing", href: "/services/ppf" },
    { label: "Ceramic coating packages", href: "/services/ceramic-coating" },
    { label: "Ceramic vs carbon vs dyed tint", href: "/ceramic-vs-carbon-vs-dyed-tint" },
    { label: "Tesla PPF", href: "/tesla-ppf" },
    { label: "Get a Quote", href: "/get-a-quote" },
    { label: "FAQ", href: "/faq" },
  ],
};

export const TINT_COMPARISON: ComparisonData = {
  path: "/ceramic-vs-carbon-vs-dyed-tint",
  title: "Ceramic vs Carbon vs Dyed Window Tint: Which Is Worth It?",
  description: "Ceramic, carbon, and dyed window tint compared: heat rejection, UV and glare, fading, signal interference, and Virginia tint law. Which film is worth it in Chantilly, VA.",
  eyebrow: "Window tint compared",
  h1: "CERAMIC VS CARBON VS DYED TINT: WHAT YOU'RE ACTUALLY PAYING FOR",
  intro: "Two cars can look identically dark and feel completely different in July traffic on Route 28. The shade is the same; the film is not. Dyed film blocks light. Carbon film blocks some heat. Ceramic film blocks most of the infrared heat without going darker or interfering with your phone, GPS, or Tesla's connectivity. Here is what separates them, and why we only install ceramic.",
  breadcrumb: "Ceramic vs Carbon vs Dyed Tint",
  columns: [
    { key: "dyed", name: "Dyed Tint", sub: "Entry-level film", bestFor: "Looks only. Cheapest way to get a dark car; fades, turns purple, and does little for heat." },
    { key: "carbon", name: "Carbon Tint", sub: "Mid-tier film", bestFor: "A step up: no purple fade and moderate heat rejection, but still well short of ceramic on infrared." },
    { key: "ceramic", name: "Ceramic Tint", sub: "GeoShield Pro Nano Ceramic", href: "/services/window-tinting", bestFor: "Real heat rejection, 99% UV, signal-safe, lifetime warranty. The only film we install." },
  ],
  rows: [
    { label: "Heat (infrared) rejection", cells: { dyed: { mark: "no", text: "Low. Dyed film absorbs light, not infrared heat; the glass still radiates into the cabin." }, carbon: { mark: "partial", text: "Moderate, roughly 40–60% IR depending on the film." }, ceramic: { mark: "yes", text: "80–83% IR rejection on GeoShield Pro Nano Ceramic." } } },
    { label: "UV rejection", cells: { dyed: { mark: "partial", text: "Most block UV early on, but the dye breaks down." }, carbon: { mark: "yes", text: "Around 99%." }, ceramic: { mark: "yes", text: "99% UV, stable for the life of the film." } } },
    { label: "Glare reduction", cells: { dyed: { mark: "yes", text: "Yes, by going dark." }, carbon: { mark: "yes", text: "Yes." }, ceramic: { mark: "yes", text: "Yes, at any shade, including light legal front windows." } } },
    { label: "Fading / turning purple", cells: { dyed: { mark: "no", text: "Yes, within 2–5 years in Virginia sun." }, carbon: { mark: "yes", text: "Does not turn purple." }, ceramic: { mark: "yes", text: "Color-stable; lifetime warranty against fading and bubbling." } } },
    { label: "Phone, GPS, key fob, EV signal", cells: { dyed: { mark: "yes", text: "No interference (no metal)." }, carbon: { mark: "yes", text: "No interference." }, ceramic: { mark: "yes", text: "Non-metalized, signal-safe." } } },
    { label: "Clarity & night visibility", cells: { dyed: { mark: "partial", text: "Can look hazy; darker shades hurt night vision." }, carbon: { mark: "partial", text: "Slight matte look on some films." }, ceramic: { mark: "yes", text: "Clearest of the three; blocks heat without needing to be dark." } } },
    { label: "Virginia-legal options", cells: { dyed: { text: "Must be 50% front / 35% rear on sedans, same as any film." }, carbon: { text: "Same limits." }, ceramic: { text: "Same limits, but a 50% ceramic front window still rejects most heat." } } },
    { label: "Warranty", cells: { dyed: { text: "Often 1–3 years, if any." }, carbon: { text: "Usually limited lifetime on the film only." }, ceramic: { text: "GeoShield nationwide lifetime warranty on film and labor at Skyline." } } },
  ],
  verdicts: [
    { title: "Skip dyed tint", body: "It is the film that turns purple and bubbles on cars you see around Fairfax County. The savings disappear the first time it has to be stripped and redone, which costs more than tinting it right once.", href: "/services/window-tinting", cta: "See ceramic tint options" },
    { title: "Carbon: fine, but ask why", body: "Carbon is a reasonable middle option at a shop that carries it. The step up to ceramic is small on a sedan, and the heat difference on a black interior in August is not small.", href: "/faq", cta: "Tint FAQ" },
    { title: "Ceramic: what we install", body: "Every car at Skyline gets GeoShield Pro Nano Ceramic. Real IR rejection, signal-safe for Teslas and EVs, and a lifetime warranty backed by us in Chantilly. Add the windshield for the full effect.", href: "/get-a-quote?service=tint", cta: "Get a tint quote" },
  ],
  faqs: [
    { q: "Is ceramic tint worth the extra cost over carbon?", a: "For most Northern Virginia drivers, yes. Ceramic rejects roughly 80% of infrared heat versus about half for carbon, so the cabin cools faster and the AC works less. The difference in price is small next to the difference in comfort, and ceramic carries a lifetime warranty." },
    { q: "Does ceramic tint have to be dark to block heat?", a: "No. Heat rejection comes from the nano-ceramic layer, not the shade. A 50% front-window ceramic film that is legal in Virginia still blocks most infrared heat and 99% of UV." },
    { q: "Does ceramic tint interfere with phone signal, GPS, or Tesla connectivity?", a: "No. GeoShield Pro Nano Ceramic is non-metalized, so it does not affect cell, GPS, satellite radio, key fobs, toll transponders, or EV connectivity. Metalized films were the ones that caused problems." },
    { q: "What tint is legal in Virginia?", a: "On sedans, front side windows must let in at least 50% of light and rear side and back windows at least 35%. SUVs, trucks, and vans may go darker behind the front doors. Only a non-reflective strip above the AS-1 line is allowed on the windshield. We install to these limits and can help with medical exemption paperwork." },
    { q: "Why does cheap tint turn purple?", a: "Dyed film uses a layer of dye to darken the glass, and UV breaks the dye down over a few years. Carbon and ceramic films get their color and performance from carbon or ceramic particles that do not degrade, so they stay the same shade for the life of the film." },
    { q: "How much does ceramic window tint cost in Chantilly, VA?", a: "It depends on how many windows you tint and the shade you choose. Every package is GeoShield Pro Nano Ceramic with a lifetime warranty. Send us your vehicle through the free quote form and we reply with an exact price, usually within the hour." },
  ],
  videoIds: ["C3k3BF33d7o", "SugVScEKEWM", "284uuWTiKAg", "pxpi-uF0eO0", "FsQ8yZxh4Es"],
  related: [
    { label: "Window tinting packages", href: "/services/window-tinting" },
    { label: "PPF vs ceramic coating", href: "/ppf-vs-ceramic-coating" },
    { label: "Tint FAQ", href: "/faq" },
    { label: "Videos", href: "/videos" },
    { label: "Get a Quote", href: "/get-a-quote" },
    { label: "Chantilly window tinting", href: "/window-tinting-chantilly-va" },
  ],
};

export const STEK_VS_XPEL: ComparisonData = {
  path: "/stek-vs-xpel-ppf",
  title: "STEK vs XPEL PPF: Why We Install STEK DYNOshield in Chantilly",
  description: "STEK DYNOshield vs XPEL Ultimate Plus, row by row: 12-year warranty, hydrophobic self-healing top coat, clarity, pattern fit, and why Skyline Customs chose STEK for Northern Virginia cars.",
  eyebrow: "STEK vs XPEL",
  h1: "STEK VS XPEL: WHY WE PUT STEK DYNOSHIELD ON EVERY CAR",
  intro: "We did not pick a film because a rep bought lunch. Before Skyline Customs standardized on one brand, we installed and lived with both STEK DYNOshield and XPEL Ultimate Plus on Northern Virginia daily drivers, the cars that eat gravel on Route 28 and I-66 every morning. Both are premium thermoplastic polyurethane films, and both stop a rock chip. STEK won our bay on the things you notice in year three and year ten: a top coat that stays clear and sheds water on its own, self-healing that keeps the hood looking new after a dozen washes, a 12-year manufacturer warranty written in plain terms, and patterns that fit the newest Teslas, BMWs, and trucks the day they come out. Here is the comparison, row by row, and what it means for your car.",
  breadcrumb: "STEK vs XPEL",
  columns: [
    { key: "stek", name: "STEK DYNOshield", sub: "What we install", href: "/services/ppf", bestFor: "Drivers who want the clearest film we have put on a car, a hydrophobic self-healing top coat built in, and a 12-year warranty behind it. The right choice for a car you plan to keep and drive hard." },
    { key: "xpel", name: "XPEL Ultimate Plus", sub: "The film we moved away from", bestFor: "A well-known film, and a fine one in the right hands. It is what most shops carry because it is what most shops have always carried, not because it won a comparison." },
    { key: "installer", name: "The Skyline Install", sub: "What the film needs to shine", href: "/get-a-quote", bestFor: "Either film fails with rushed prep and trimmed edges. DYNOshield gets our full process: decontamination, correction, plotter-cut patterns, wrapped edges, and a walk-and-pay inspection under lights." },
  ],
  rows: [
    { label: "Film material", cells: { stek: { mark: "yes", text: "Thermoplastic polyurethane with a glossy top coat engineered for clarity on dark paint." }, xpel: { mark: "yes", text: "Thermoplastic polyurethane as well. On raw material the two are close, which is why the top coat decides it." }, installer: { text: "A strong base film only matters if the surface under it was corrected and cleaned first. Ours is." } } },
    { label: "Self-healing top coat", cells: { stek: { mark: "yes", text: "DYNOshield\'s top coat closes wash swirls and light scratches with sunlight or warm water, wash after wash." }, xpel: { mark: "partial", text: "Ultimate Plus self-heals too; in our bay the DYNOshield top coat recovered faster and more completely after the same scratch test." }, installer: { text: "Self-healing fixes surface marring. It never fixes an edge that lifted because it was trimmed short on the panel." } } },
    { label: "Hydrophobic finish", cells: { stek: { mark: "yes", text: "Built into the DYNOshield top coat from the roll: water beads and dirt rinses off before you add any coating." }, xpel: { mark: "partial", text: "XPEL describes a hydrophobic finish on Ultimate Plus; owners we see still ask for a coating to get the beading DYNOshield has on day one." }, installer: { text: "We still recommend a Gtechniq coating over the film for gloss and easier washing. On DYNOshield it bonds to a surface that already sheds water." } } },
    { label: "Clarity and yellowing", cells: { stek: { mark: "yes", text: "Optically clear on black, white, and metallic paint, with yellowing, cracking, and staining covered under the STEK warranty." }, xpel: { mark: "partial", text: "Clear on install. Yellowing is addressed under XPEL\'s own terms, which you should read directly before you book." }, installer: { text: "Most yellowing we remove from older installs was dirt sealed under the film by a rushed prep. Our wash-correct-wipe sequence is why DYNOshield stays invisible." } } },
    { label: "Warranty", cells: { stek: { mark: "yes", text: "12-year manufacturer warranty, one number, no product-line footnotes." }, xpel: { mark: "partial", text: "Terms vary by product line and have changed over time. Read XPEL\'s current Ultimate Plus warranty rather than a shop\'s summary." }, installer: { text: "The manufacturer covers the film. Skyline covers the labor: if an edge we wrapped lifts, we fix it." } } },
    { label: "Patterns and cutting", cells: { stek: { mark: "yes", text: "Plotter-cut from STEK\'s pattern library for the exact year and trim, including the Tesla Juniper and Highland refreshes, cut off the car every time." }, xpel: { mark: "yes", text: "XPEL\'s pattern library is large and well maintained. This row is close." }, installer: { text: "Patterns are only half of it. We wrap the film under the hood lip and into the bumper and fender gaps, so there is no exposed edge to catch dirt." } } },
    { label: "Edges and visible lines", cells: { stek: { mark: "yes", text: "DYNOshield stretches and conforms well around bumper curves and mirror caps, so our wrapped edges stay down." }, xpel: { mark: "partial", text: "Conforms well too, but a trimmed-on-the-panel XPEL edge lifts and collects dirt like any other film\'s." }, installer: { mark: "yes", text: "No blades on your paint, every edge wrapped, and you inspect each one under lights before paying the balance." } } },
    { label: "Prep before the film goes on", cells: { stek: { mark: "yes", text: "Decontamination wash, paint enhancement or correction, then a solvent wipe so the adhesive bonds to bare clear coat." }, xpel: { mark: "partial", text: "XPEL recommends similar prep. Whether a given shop does it is a different question, and skipped prep is the most common complaint we hear about other installs." }, installer: { text: "If a quote promises a full front in two hours, something on this list was skipped." } } },
    { label: "Removal years later", cells: { stek: { mark: "yes", text: "Lifts cleanly from factory paint with heat when you sell or re-film the car." }, xpel: { mark: "yes", text: "Also removable without harming original paint when it was installed without blade cuts." }, installer: { text: "Clean removal depends on original paint underneath and an install with no cuts on the panel. That is how we work." } } },
    { label: "Our verdict", cells: { stek: { mark: "yes", text: "The film we trust on our own cars: clearest finish, best top coat, longest plain-language warranty, patterns that fit what Northern Virginia drives." }, xpel: { text: "A good film we chose not to carry. If another shop installs it well you will be fine, but you will not get the DYNOshield top coat or the 12-year term." }, installer: { text: "Film plus process. Send us the year and trim and we will tell you exactly what we would do to it." } } },
  ],
  verdicts: [
    { title: "Choose STEK DYNOshield if…", body: "You want the clearest film on the market with a hydrophobic self-healing top coat built in, a 12-year manufacturer warranty, and patterns cut for your exact car, installed in a dust-controlled bay in Chantilly where you inspect every edge under lights before paying the balance.", href: "/services/ppf", cta: "See our PPF packages" },
    { title: "XPEL is acceptable if…", body: "A shop you already trust carries it and shows you wrapped edges on a car they finished this week. Just know what you are giving up: the DYNOshield top coat and the single 12-year warranty term.", href: "/partial-front-vs-full-front-ppf", cta: "Pick your coverage" },
    { title: "Either way, see the shop", body: "Look at edges on a finished car, ask about prep, and ask who covers the labor. Then send us your car and compare the answers.", href: "/get-a-quote", cta: "Request a free quote" },
  ],
  faqs: [
    { q: "Is STEK better than XPEL?", a: "For the cars we see in Northern Virginia, yes. Both are premium polyurethane films that stop rock chips, but STEK DYNOshield gives you a hydrophobic self-healing top coat from the roll, exceptional clarity on dark paint, and a single 12-year manufacturer warranty. That is why we standardized on it after installing both." },
    { q: "Why did Skyline Customs switch to STEK DYNOshield?", a: "Three things decided it: the top coat stays clearer and sheds water better over years of washes, the 12-year warranty is one plain number instead of terms that vary by product line, and STEK\'s patterns fit the newest Teslas, BMWs, and trucks our customers bring in. Running one film also means every installer in the bay knows exactly how it stretches and seals." },
    { q: "Does STEK DYNOshield self-heal like XPEL Ultimate Plus?", a: "Yes, and in our bay it recovers faster. Wash swirls and light scratches in the DYNOshield top coat close with sun or a pour of warm water. Self-healing covers surface marring on either film, not a stone that cuts through, so the film\'s thickness and the edge work still matter." },
    { q: "What is the warranty on STEK paint protection film?", a: "STEK DYNOshield carries a 12-year manufacturer warranty against yellowing, cracking, staining, and delamination, and Skyline covers the labor on every edge we wrap. XPEL\'s terms differ by product line and change over time, so read XPEL\'s current warranty directly before trusting a competitor\'s summary." },
    { q: "Can I still get a good result with XPEL from another shop?", a: "You can, if that shop preps properly, cuts patterns off the car, wraps the edges, and inspects the car with you. Ask to see a finished car first. What you will not get is the DYNOshield top coat or the 12-year term, which is why we moved every car in our bay to STEK." },
  ],
  videoIds: ["P2zyuOrWiDA", "n5mQVftEwfA"],
  reelCodes: ["DaNiBH6u8Y4"],
  videoIntro: "First clip: a hacksaw, a razor blade, and a fistful of gravel against a fender we had just wrapped in STEK DYNOshield. Then a look at how the film disappears on a finished car and the prep that makes it bond.",
  related: [
    { label: "Our PPF packages", href: "/services/ppf" },
    { label: "Partial vs full front PPF", href: "/partial-front-vs-full-front-ppf" },
    { label: "PPF vs ceramic coating", href: "/ppf-vs-ceramic-coating" },
    { label: "Request a free quote", href: "/get-a-quote" },
  ],
};

export const PARTIAL_VS_FULL_FRONT: ComparisonData = {
  path: "/partial-front-vs-full-front-ppf",
  title: "Partial Front vs Full Front PPF: Which Coverage Do You Need?",
  description: "Partial front, full front, and full front extended PPF compared: what each covers, where the hood line falls, chip exposure on I-66 and Route 28, and leases.",
  eyebrow: "PPF coverage compared",
  h1: "PARTIAL FRONT VS FULL FRONT PPF: WHERE SHOULD THE FILM STOP?",
  intro: "Every paint protection film quote comes down to one question: how far up the car does the film go? A partial front covers the bumper and the leading edge of the hood. A full front covers the panels that face the airstream at highway speed. Full front extended adds the rockers and door edges that take parking-lot abuse. We install all three in Chantilly, and we recommend full front to most daily drivers. This page explains why, and when the other two are the smarter call.",
  breadcrumb: "Partial vs Full Front",
  columns: [
    { key: "partial", name: "Partial Front", sub: "Bumper, leading 18 inches of hood, fender edges, mirrors", href: "/services/ppf", bestFor: "Garage-kept weekend cars, short leases, and anyone who needs to protect the bumper now and the rest later." },
    { key: "full", name: "Full Front", sub: "Our recommendation", href: "/services/ppf", bestFor: "Daily drivers on I-66, Route 28, and the Dulles Toll Road. Covers the panels that take highway gravel with no seam across the hood." },
    { key: "extended", name: "Full Front Extended", sub: "Adds rockers, door edges, door cups", href: "/get-a-quote?service=ppf", bestFor: "Trucks, SUVs, and cars parked in tight garages, where door edges and rockers take as much punishment as the bumper." },
  ],
  rows: [
    { label: "What is covered", cells: { partial: { text: "Front bumper, the leading 18 inches of the hood, the front edges of both fenders, and the mirror caps." }, full: { text: "The entire hood, front bumper, both fenders, mirror caps, headlights, and A-pillars." }, extended: { text: "Everything in full front plus rocker panels, door edges, and the door cups behind the handles." } } },
    { label: "The hood line", cells: { partial: { mark: "no", text: "Film stops partway up the hood, leaving a seam across the middle of the panel." }, full: { mark: "yes", text: "The whole hood is filmed and the edge is wrapped under the lip, so there is no line to find." }, extended: { mark: "yes", text: "Identical hood coverage to full front." } } },
    { label: "Chip exposure on I-66 and Route 28", cells: { partial: { mark: "partial", text: "The bumper is protected; the upper hood, fender tops, and headlights still take gravel at highway speed." }, full: { mark: "yes", text: "Covers where the stones land. The car ahead throws them into the hood, fenders, and lights." }, extended: { mark: "yes", text: "Full highway coverage plus the rockers that catch spray and debris from your own front tires." } } },
    { label: "Headlights and A-pillars", cells: { partial: { mark: "no", text: "Not included; headlight lenses pit and haze without film." }, full: { mark: "yes", text: "Headlights and A-pillars are filmed." }, extended: { mark: "yes", text: "Included, same as full front." } } },
    { label: "Door edges, rockers, door cups", cells: { partial: { mark: "no", text: "Not covered." }, full: { mark: "no", text: "Not part of the package; this is the one gap on a full front." }, extended: { mark: "yes", text: "Rockers, door edges, and door cups are filmed to stop dings, rock rash, and fingernail scratches." } } },
    { label: "Visible edges", cells: { partial: { mark: "partial", text: "The hood seam is visible up close on light colors and collects a faint line of wax or dirt over time." }, full: { mark: "yes", text: "Edges wrap under the hood, fenders, and bumper, so the film disappears." }, extended: { mark: "yes", text: "Rocker and door edge pieces are wrapped or tucked into the seams." } } },
    { label: "Install time", cells: { partial: { text: "A few hours, in and out the same day." }, full: { text: "Usually one day; two when a Gtechniq ceramic coating is added over the film." }, extended: { text: "One to two days depending on the vehicle and whether a coating is added." } } },
    { label: "Resale and trade-in", cells: { partial: { mark: "partial", text: "The bumper looks new; a chipped upper hood on a dark car is the first thing a buyer or appraiser notices." }, full: { mark: "yes", text: "The front end photographs and appraises like new because the panels buyers inspect are the ones protected." }, extended: { mark: "yes", text: "Adds clean door edges and rockers, which matter on trucks and SUVs that get looked over closely." } } },
    { label: "Leased cars", cells: { partial: { mark: "partial", text: "Protects the bumper, which lease-return inspectors check, but leaves the hood exposed for the length of the lease." }, full: { mark: "yes", text: "Covers the panels lease returns get charged for, and the film comes off cleanly before turn-in." }, extended: { mark: "partial", text: "Worthwhile on a longer lease or a truck; otherwise more coverage than a two-year lease needs." } } },
    { label: "When it makes sense", cells: { partial: { text: "A car that rarely sees the highway, or a budget that needs to be split across two visits." }, full: { text: "Any car that commutes, road-trips, or sits in traffic behind dump trucks on Route 28." }, extended: { text: "Lifted trucks, SUVs with wide rockers, and anything that lives in a tight parking garage." } } },
  ],
  verdicts: [
    { title: "Full front for most daily drivers", body: "If the car sees I-66 or Route 28 more than a couple of times a week, the upper hood will chip, and the hood is the panel you cannot hide. Full front has no seam, covers the headlights, and is usually done in one day.", href: "/services/ppf", cta: "Full front details" },
    { title: "Partial front has its place", body: "A garage-kept car that drives local on weekends, or a short lease where the bumper is the only panel you are worried about, does fine with partial coverage. Just know where the line will be before you commit.", href: "/ppf-cost", cta: "How coverage is priced" },
    { title: "Extended for trucks and tight parking", body: "Rocker panels on a lifted truck catch gravel from the front tires, and door edges in a garage take dings from the car next to you. If that describes your parking spot, extended coverage pays for itself in avoided touch-ups.", href: "/get-a-quote?service=ppf", cta: "Quote extended coverage" },
  ],
  faqs: [
    { q: "Is partial front PPF worth it?", a: "For a car that mostly stays off the highway, yes. The bumper takes the most abuse at low speed and a partial front protects it fully. The trade-off is a seam partway up the hood and no coverage on the upper hood, fender tops, or headlights, which is where highway gravel lands." },
    { q: "Can you see the line where partial front PPF stops?", a: "Up close, usually yes, especially on white, silver, and other light colors. The edge sits in the middle of a flat panel, so there is nothing to wrap it under. A full front moves that edge under the hood lip where it disappears." },
    { q: "How long does full front PPF take to install?", a: "Usually a single day at our Chantilly shop. Drop the car off in the morning and pick it up that afternoon after you inspect it under the lights with us. Adding a Gtechniq ceramic coating over the film turns it into a two-day job." },
    { q: "Should I get full front extended on an SUV or truck?", a: "If it is lifted, parked in tight spots, or driven on gravel, yes. Wide rocker panels on trucks and SUVs catch stones the front tires throw back, and door edges collect dings in parking garages. On a sedan that parks in a driveway, a standard full front is usually enough." },
    { q: "Can I start with partial front and upgrade to full front later?", a: "You can, but the partial hood piece has to be removed and the hood re-filmed as one panel, so you end up paying for the hood twice. If a full front is the goal, it is less expensive overall to do it in one visit." },
  ],
  videoIds: ["LQ1iXlQpXGc", "ZvVdjXH06ug"],
  related: [
    { label: "PPF packages and what each covers", href: "/services/ppf" },
    { label: "How PPF is priced", href: "/ppf-cost" },
    { label: "Tesla Model Y PPF", href: "/tesla-model-y-ppf" },
    { label: "Request a free quote", href: "/get-a-quote" },
  ],
};

export const CERAMIC_VS_WAX: ComparisonData = {
  path: "/ceramic-coating-vs-wax",
  title: "Ceramic Coating vs Wax vs Sealant: How Long Each Lasts",
  description: "Carnauba wax, paint sealant, and Gtechniq ceramic coating compared: durability, gloss, chemical and UV resistance, washing, swirls, and who should pick which.",
  eyebrow: "Ceramic coating vs wax",
  h1: "CERAMIC COATING VS WAX VS SEALANT: WHAT A SATURDAY OF WAXING ACTUALLY BUYS YOU",
  intro: "Carnauba wax, synthetic sealant, and a professional ceramic coating all make paint shine and bead water on day one. The difference shows up on day sixty. Wax is gone after a few washes, a sealant hangs on for a season, and a Gtechniq coating is still shedding water years later. None of the three will stop a rock chip; that job belongs to paint protection film. Here is how the three stack up for a car that lives through Northern Virginia pollen, road salt, and July sun.",
  breadcrumb: "Ceramic vs Wax",
  columns: [
    { key: "wax", name: "Carnauba Wax", sub: "Traditional paste or liquid", bestFor: "Enthusiasts who enjoy the ritual and want a warm, deep glow on a garage-kept car for a show or a weekend." },
    { key: "sealant", name: "Paint Sealant", sub: "Synthetic polymer", bestFor: "Owners who detail their own car a few times a year and want protection that outlasts wax without a professional install." },
    { key: "ceramic", name: "Gtechniq Ceramic Coating", sub: "Crystal Serum Light or Ultra", href: "/services/ceramic-coating", bestFor: "Anyone who wants the car to stay glossy and easy to rinse for years, with a written warranty, and never wants to wax again." },
  ],
  rows: [
    { label: "Durability", cells: { wax: { mark: "no", text: "A few weeks to a couple of months; heat and detergent strip it quickly." }, sealant: { mark: "partial", text: "Several months, depending on how often the car is washed and where it is parked." }, ceramic: { mark: "yes", text: "Crystal Serum Light is warrantied for 5 years and Crystal Serum Ultra for 7." } } },
    { label: "Gloss and depth", cells: { wax: { mark: "yes", text: "The warmest, deepest look of the three, which is why show cars still get waxed." }, sealant: { mark: "partial", text: "Sharp, glassy reflection that reads a little cooler than carnauba." }, ceramic: { mark: "yes", text: "Hard, candy-like gloss locked over corrected paint, and it does not fade between applications because there are none." } } },
    { label: "Chemical resistance", cells: { wax: { mark: "no", text: "Bird droppings, bug splatter, and tree sap etch through wax within hours." }, sealant: { mark: "partial", text: "Buys a little more time before etching, but still needs quick cleanup." }, ceramic: { mark: "yes", text: "Resists the acids in droppings, sap, and road salt long enough for a normal wash to remove them." } } },
    { label: "UV protection", cells: { wax: { mark: "partial", text: "Some UV filtering while the wax lasts, which is not long in a Fairfax County parking lot." }, sealant: { mark: "partial", text: "Moderate UV filtering for the life of the layer." }, ceramic: { mark: "yes", text: "Blocks UV for years and keeps the clear coat from chalking and dulling." } } },
    { label: "Washing and water behavior", cells: { wax: { mark: "partial", text: "Beads nicely for a few weeks, then dirt starts sticking again." }, sealant: { mark: "yes", text: "Slick surface for a season; dirt releases with less scrubbing." }, ceramic: { mark: "yes", text: "Rinse, foam, rinse, dry. Grime does not bond to a coated surface, so washing takes a fraction of the time." } } },
    { label: "Swirl and scratch resistance", cells: { wax: { mark: "no", text: "Soft, offers no real resistance to wash marring." }, sealant: { mark: "no", text: "Thin and soft; swirls come from wash technique, not the sealant." }, ceramic: { mark: "partial", text: "Harder than clear coat, so careful washing leaves fewer swirls, but a dirty mitt still marks it." } } },
    { label: "Rock chips", cells: { wax: { mark: "no", text: "No. Wax is a fraction of a hair thick." }, sealant: { mark: "no", text: "No. A polymer layer cannot absorb an impact." }, ceramic: { mark: "no", text: "No, and any shop that tells you otherwise is selling. STEK paint protection film is the only product here that stops a chip." } } },
    { label: "Cost of ownership, in hours", cells: { wax: { text: "An afternoon of washing, claying, and waxing every month or two, for as long as you own the car." }, sealant: { text: "A full day of prep and application a few times a year, plus top-up sprays in between." }, ceramic: { text: "One shop visit, then normal washing. No reapplication for the warranty period." } } },
    { label: "Prep required", cells: { wax: { text: "Wash and clay; wax hides light swirls, which is part of its appeal." }, sealant: { text: "Wash, clay, and ideally a polish, because sealant shows what is beneath it." }, ceramic: { text: "Decontamination wash and paint correction are mandatory, because the coating seals in every defect left behind." } } },
    { label: "Who should pick it", cells: { wax: { text: "The owner who likes spending Saturday mornings in the garage with a towel." }, sealant: { text: "The owner who details twice a year and wants the car to look good in between." }, ceramic: { text: "The owner who wants the car to look corrected and glossy for years without thinking about it." } } },
  ],
  verdicts: [
    { title: "Wax if you love the process", body: "There is nothing wrong with carnauba on a garage-kept car you enjoy detailing. Accept that it is cosmetic and temporary, and plan on redoing it every few weeks through a Virginia summer.", href: "/ppf-vs-ceramic-coating", cta: "What actually protects paint" },
    { title: "Sealant if you detail yourself", body: "A quality sealant is the sensible middle ground for a hands-on owner. It lasts a season, beads well, and costs you a weekend a few times a year instead of a shop visit.", href: "/services/ceramic-coating", cta: "Compare with a coating" },
    { title: "Ceramic if you want it done once", body: "A Gtechniq coating applied over corrected paint in our Chantilly bay turns washing into a rinse-and-dry job and carries a 5- or 7-year warranty. Pair it with film on the front end and the car is covered against both etching and chips.", href: "/get-a-quote?service=ceramic", cta: "Get a coating quote" },
  ],
  faqs: [
    { q: "How long does a ceramic coating last compared to wax?", a: "A carnauba wax lasts a few weeks to a couple of months before it washes away. A paint sealant typically lasts a season. Gtechniq Crystal Serum Light is warrantied for 5 years and Crystal Serum Ultra for 7, as long as the car is washed properly and kept out of automatic brush washes." },
    { q: "Can I wax over a ceramic coating?", a: "You can, but there is no reason to. Wax sits on top of the coating, dulls its hydrophobic behavior, and washes off in weeks while the coating underneath is unchanged. A coating-safe maintenance spray is the right way to refresh it." },
    { q: "Does a ceramic coating stop rock chips or scratches?", a: "It does not stop chips. A coating is microns thick and resists chemicals, UV, and light marring, not impacts. Rock chips on the hood and bumper are what STEK paint protection film is for, and we apply the coating over the film and the rest of the paint." },
    { q: "Do I need paint correction before a ceramic coating?", a: "Yes. The coating locks in whatever is under it for years, so swirls and water spots left behind become permanent until the coating is polished off. Every coating package at Skyline includes a decontamination wash and paint correction before the Gtechniq goes on." },
    { q: "How do I wash a ceramic coated car?", a: "Two buckets or a foam cannon, a clean microfiber mitt, and a pH-neutral soap. Rinse, wash top to bottom, rinse again, and dry with a plush towel or blower. Skip automatic brush washes, which can mar any finish, coated or not." },
  ],
  videoIds: ["n5mQVftEwfA", "P2zyuOrWiDA"],
  related: [
    { label: "Ceramic coating packages", href: "/services/ceramic-coating" },
    { label: "PPF vs ceramic coating", href: "/ppf-vs-ceramic-coating" },
    { label: "Paint protection film", href: "/services/ppf" },
    { label: "Request a free quote", href: "/get-a-quote" },
  ],
};

/** The comparison guides that are routed from data (the two older ones have their own pages). */
export const COMPARISON_PAGES: ComparisonData[] = [STEK_VS_XPEL, PARTIAL_VS_FULL_FRONT, CERAMIC_VS_WAX];
