/**
 * PPF questions in the wording Google shows in its "People also ask" box for
 * "ppf near me" and the full-front questions Search Console reports for this
 * site. Each answer is direct, 40–80 words, and names the shop's own products so
 * that when Google lifts one into that box the answer is ours.
 *
 * Shown on /faq (own group), /services/ppf, and three per city PPF page.
 * Rules: no prices, no full-body coverage, three packages only.
 */
export interface PpfQuestion { id: string; q: string; a: string; href?: string; hrefLabel?: string }

export const PPF_QUESTIONS: PpfQuestion[] = [
  { id: "cost", q: "How much does a typical PPF cost?", a: "It depends on how much of the car you cover and how big the car is. Partial front is the entry point, full front (hood, bumper, fenders, mirrors, headlights, A-pillars) is what most daily drivers choose, and full front extended adds rockers and door edges. Skyline Customs replies to a free quote with an exact price, usually within the hour.", href: "/ppf-cost", hrefLabel: "What drives PPF pricing" },
  { id: "worth", q: "Is doing PPF worth it?", a: "For a car that is driven, yes. One rock chip on a bumper or hood means a repaint that never quite matches and lowers trade-in value. Full front film in self-healing STEK DYNOshield takes those hits for 12 years under warranty, and the paint underneath stays factory. The math is simple on any car you plan to keep more than a couple of years." },
  { id: "install-time", q: "How long does PPF installation take?", a: "Partial front is about half a day, full front is one day, and full front extended is one to two days. Every install at Skyline Customs starts with a decontamination wash and paint inspection and ends with a walk-around under high-intensity lighting before you pick up." },
  { id: "disadvantages", q: "What are the disadvantages of PPF?", a: "It costs more up front than a coating, it only protects the panels it covers, it cannot hide chips that are already there, and a poor install shows: lifted edges, dirt under the film, visible seams. It also wants hand washing rather than brush car washes. Every one of those is solved by covering the right panels and using a certified installer with computer-cut patterns." },
  { id: "car-wash", q: "Can I go through a car wash with PPF?", a: "Touchless washes are fine once the film has cured for seven days. Skip brush and cloth washes: the spinning brushes drag grit across the film and can catch an edge. Hand washing with a pH-neutral soap and two buckets keeps the self-healing top coat clear for the life of the film.", href: "/blog/how-to-wash-and-care-for-ppf", hrefLabel: "How to wash a car with PPF" },
  { id: "lifespan", q: "How long will a PPF last?", a: "Ten to twelve years or more with hand washing. STEK DYNOshield carries a 12-year manufacturer warranty against yellowing, cracking, peeling, and delamination, and the film on cars we did in our first years still looks clear.", href: "/blog/how-long-does-ppf-last-northern-virginia", hrefLabel: "What to expect year by year" },
  { id: "worth-2026", q: "Is PPF worth it in 2026?", a: "More than ever. Factory paint keeps getting thinner, especially on EVs, bumper repaints keep getting more expensive because of the sensors and cameras in them, and modern film has improved: STEK DYNOshield self-heals, resists yellowing, and is warrantied for 12 years. The film costs about what it did five years ago. The repaint it prevents does not." },
  { id: "wax", q: "Can you wax a car with PPF?", a: "You can, but a ceramic coating or a spray sealant does the job better. Waxes with dyes, abrasives, or petroleum solvents can stain or dull the film's top coat, and wax builds up along edges. We coat film with Gtechniq Crystal Serum, which adds gloss and makes the self-healing surface shed grit for years instead of weeks." },
  { id: "rock-chips", q: "Will PPF stop rock chips?", a: "Yes. Paint protection film is the only product that physically absorbs a stone impact. STEK DYNOshield is roughly eight thousandths of an inch of urethane, several times thicker than a clear coat, so a stone that would punch through paint leaves a mark on the film that relaxes out in the sun.", href: "/blog/does-ppf-stop-rock-chips-i-66-route-28-northern-virginia", hrefLabel: "Rock chips on I-66 and Route 28" },
  { id: "buff", q: "Can you buff out PPF?", a: "Light scratches and swirls do not need buffing. Warm water or an hour in the sun and the self-healing top coat relaxes them out. Deeper marks can be hand polished with a fine, film-safe polish, but never a heavy compound or a wool pad, which burn through the top coat. A cut that goes through the film is replaced, one panel at a time." },
  { id: "five-years", q: "How does PPF look after 5 years?", a: "Properly installed STEK DYNOshield looks like year one at year five: clear, no yellowing, no lifted edges. The tell is usually a slight pitting on the leading edge of the hood from sand, which is the film doing its job. The paint under it looks the way it did the day we filmed it." },
  { id: "avoid", q: "What not to use on PPF?", a: "No abrasive polishes or rubbing compounds, no brush car washes, no pressure washer tip closer than a foot to an edge, no solvent-heavy bug or tar removers, and no waxes with dyes. Use pH-neutral soap, microfiber, and a film-safe sealant or ceramic coating." },
  { id: "alternative", q: "Is there an alternative to PPF?", a: "Not for impacts. A ceramic coating makes a car easier to wash and keeps it glossy, but it is microns thick and a stone goes straight through it. Touch-up paint hides a chip after the fact. Film is the only thing that stops the chip from happening, which is why the two work best together: film on the front, coating over everything." },
  { id: "wash-how", q: "How do I wash a car with PPF?", a: "Wait seven days after the install, then hand wash: rinse first, two buckets, pH-neutral soap, a clean microfiber mitt, straight strokes rather than circles, and a microfiber drying towel. Touchless washes are fine. Avoid brush washes and keep pressure-washer tips away from the film's edges.", href: "/blog/how-to-wash-and-care-for-ppf", hrefLabel: "The full care routine" },
  { id: "ppf-vs-ceramic", q: "Is PPF better or ceramic?", a: "They do different jobs. PPF stops rock chips and scratches on the panels it covers. Ceramic coating keeps every panel glossy and easy to wash but stops no impacts. For a daily driver on Northern Virginia highways the right answer is both: full front film, then Gtechniq ceramic over the whole car.", href: "/ppf-vs-ceramic-coating", hrefLabel: "PPF vs ceramic coating, compared" },
  { id: "order", q: "What goes on first, PPF or ceramic coating?", a: "Film first, always. Ceramic coating cures into a slick surface that film cannot bond to, so coating a panel and then filming it means lifted edges. The right order is paint correction, PPF on the panels you are covering, then ceramic coating over the film and the bare paint together." },
  { id: "best-brand", q: "What is the best brand for PPF coating?", a: "We install STEK DYNOshield and nothing else. It self-heals, carries a 12-year warranty, and has the best resistance to yellowing and staining of any film we have tested. XPEL and 3M are good films too; the install matters more than the brand name, and STEK gives us the clearest, most stain-resistant top coat to install.", href: "/stek-vs-xpel-ppf", hrefLabel: "STEK vs XPEL" },
  { id: "downside", q: "What is the downside of PPF?", a: "The only real downside is that it has to be installed well. Hand-cut film shows seams and risks a blade on your paint; bulk film yellows. That is why we use computer-cut STEK patterns for your exact year and model, wrap edges where the pattern allows, and install in a dust-controlled bay. Done right, the downside is the invoice." },
  { id: "not-worth", q: "Why is PPF not worth it?", a: "It is not worth it on a car you are selling in a few months, a car with chips and faded paint already on it, or a car that never leaves a garage. For a car you drive on I-66, Route 28, or the Beltway and plan to keep, it is one of the few things you can buy that pays for itself." },
  { id: "ten-years", q: "What happens to PPF after 10 years?", a: "STEK DYNOshield is warrantied through year twelve, so at ten the film should still be clear and bonded. If it has taken a decade of stones you may see pitting on the leading edges. At that point the film comes off cleanly with heat, the paint underneath is still factory, and a fresh set of film goes on." },
  { id: "best-coating", q: "Which car coating is best?", a: "For stopping damage, paint protection film. For gloss and easy washing, a professional ceramic coating: Gtechniq Crystal Serum Light for five years or Crystal Serum Ultra for seven. Consumer spray coatings last months, not years. The best setup for a daily driver is film on the front and Gtechniq over the whole car." },
  { id: "full-front-covers", q: "What does full front PPF cover?", a: "Full front PPF covers the full hood, the front bumper, both front fenders, the mirror caps, the headlights, and the A-pillars: every surface that faces forward and takes stones at highway speed. Partial front covers the bumper, the leading 18 inches of the hood, fender edges, and mirrors. Full front extended adds rocker panels and door edges.", href: "/partial-front-vs-full-front-ppf", hrefLabel: "Partial vs full front, compared" },
  { id: "full-front-means", q: "What does full front PPF include?", a: "Everything from the A-pillars forward: full hood, bumper, both fenders, mirrors, headlights, and the A-pillars, in computer-cut STEK DYNOshield with edges wrapped where the pattern allows. It does not include doors, rockers, or the roof. Full front extended adds the rocker panels and door edges for cars that see gravel.", href: "/services/ppf", hrefLabel: "Full front PPF at Skyline Customs" },
  { id: "body-type", q: "How does full front PPF differ by body type?", a: "The panels are the same, the amount of film is not. A truck or SUV has a taller, flatter hood and bumper that catch more stones, and a longer rocker line that most owners add with the extended package. EVs have thin paint and sensors in the bumper that our patterns cut around. Sports cars sit low, so the front splitter and rockers take hits a sedan never sees.", href: "/truck-ppf", hrefLabel: "PPF for trucks, SUVs, and EVs" },
  { id: "which-package", q: "Which PPF package is right for me?", a: "Partial front if the car mostly sees surface streets and you want the bumper and hood edge covered. Full front if you commute on I-66, Route 28, Route 7, or I-95: that is where chips land past the 18-inch hood line. Full front extended if you also drive gravel or park nose-in on rough lots. Send us the year, make, model, and how you drive, and we will tell you which one.", href: "/get-a-quote", hrefLabel: "Get a quote" },
];

/** Questions that the PPF service page already answers in its own FAQ; skipped there to avoid near-duplicates. */
export const PPF_QUESTIONS_COVERED_ON_SERVICE_PAGE = new Set(["cost", "lifespan", "worth", "install-time", "wash-how", "ppf-vs-ceramic"]);
