export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  telegramBotToken: process.env.TELEGRAM_BOT_TOKEN ?? "",
  telegramOwnerId: process.env.TELEGRAM_OWNER_ID ?? "",
  ghlApiKey: process.env.GHL_API_KEY ?? "",
  ghlLocationId: process.env.GHL_LOCATION_ID ?? "",
  googlePlacesApiKey: process.env.GOOGLE_PLACES_API_KEY ?? "",
  googlePlaceId: process.env.GOOGLE_PLACE_ID ?? "ChIJNW7sCXJFtokRVBtPKs11cNI",
  instagramAccessToken: (process.env.INSTAGRAM_ACCESS_TOKEN ?? "").trim(),
  // @skylinecustomshop Instagram Business account id (via the Skyline Customs Facebook Page).
  instagramUserId: (process.env.INSTAGRAM_USER_ID ?? "17841477151858349").trim(),
  instagramAppId: (process.env.INSTAGRAM_APP_ID ?? "").trim(),
  instagramAppSecret: (process.env.INSTAGRAM_APP_SECRET ?? "").trim(),
};
